### PR TITLE
Updates TF version for non armv7l devices

### PR DESCRIPTION
**Pull request by adiazulay**

### CODE REVIEW

**Comment by adammenges** [comment]
Any reason you can see not to merge this? cc @shawncal @adiazulay

**Comment by adammenges** [comment]
Also will help with out dependabot alert:

image

**Comment by adiazulay** [comment]
@adammenges, yup this PR is meant to address the dependabot alert.

**Comment by adammenges** [comment]
Sweet. Looks good to me if you want to merge away.

**Pull request merged**
